### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by JanSimek** [mkorz/IntegraPy#3]
I get the following error:

```
-- ------------- --
-- Receving data --
<<<0xFE ('þ')
<<<0xFE ('þ')
<<<0xEE ('î')
<<<0x4 ('')
<<<0x1 ('')
<<<0x29 (')')
<<<0x56 ('V')
<<<0xFD ('ý')
<<<0x73 ('s')
<<<0x74 ('t')
<<<0x75 ('u')
<<<0x70 ('p')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x31 ('1')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0x20 (' ')
<<<0xD8 ('Ø')
<<<0x81 ('')
<<<0xFE ('þ')
')<0xD ('
-- ------------- --
Traceback (most recent call last):
  File "integrademo.py", line 263, in <module>
    iOutputs()
  File "integrademo.py", line 201, in iOutputs
    o += str(8 * i + b + 1) + " " + iName(8 * i + b + 1, OUTPUT) + ": ON\n"
  File "integrademo.py", line 172, in iName
    return r[3:].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
```

To fix this I had to change line [172](https://github.com/mkorz/IntegraPy/blob/master/integrademo.py#L172)

``` python
    return r[3:].decode("utf-8")
```

to

``` python
    return r[3:].decode("utf-8", "ignore")
```

I have no experience with Python and I don't know what these invalid characters at the end of the message contain.

Complete log with DEBUG=1: http://pastebin.com/mNP1diEQ

**Comment by mkorz** [comment]
Hey Jan,

Many thanks for the detailed report - the debug log you has included helped me to isolate the issue.
The problem was caused by me not handling properly the names containing characters from the outside of the ASCIII set.
In your case it was the label  "Output 1" which was been translated in your Integra to Czech. 

Your solution would work as a workaround, but most likely it would drop the unrecognised characters.

Unfortunately, I cannot think of any good way of automatically detecting the correct encoding - the Integra does not seem to return the language (can only report whether it is English or not) and even that would not guarantee that all of the names used for zones or outputs contains only ASCII characters.

Instead, I decided to add the "encoding" option to the config file - I default it to the "cp1250", 
which should work for you. 

Please pull and let me know if this solves the issue for you.

Thanks again for your report.
Marcin

**Comment by JanSimek** [comment]
Hello Marcin, thank you for the quick fix. I began to write a [web interface](https://github.com/JanSimek/phpintegra) to my Integra system and your script was my starting point. I would have never been able to make any progress without it, so thank you very much.

**Comment by mkorz** [comment]
Hi Jan,
You are welcome - great to hear you found a use for it :). Let me know if you find more bugs (there bound to be some) or if you need anything added.
Your web interface looks cool!
